alexandrevilain/temporal-operator

api/v1beta1/temporalcluster_defaults.go, pkg/resource/ui_deployment_builder.go
=> fix(ui): ensure TEMPORAL_UI_PORT is always set to prevent conflicts with k8s discovery environment variables

internal/resource/persistence/template.go
When I try to change the index name, I've got an error on the update visibility index, from this [step](https://github.com/alexandrevilain/temporal-operator/blob/6fe41feeba75135156a7ad8d5f1819320b2a6061/internal/resource/persistence/template.go#L156)
=> change hardcode index name for using from env vars {{ .Indices.Visibility }}

webhooks/temporalcluster_webhook.go, webhooks/temporalcluster_webhook_test.go
=> fix webhook regression: ensure numHistoryShards is immutable

api/v1beta1/temporalcluster_types.go, config/crd/bases/temporal.io_temporalclusters.yaml, internal/resource/persistence/schema_setup_job_builder.go, pkg/temporal/archival/archival.go
Hello!
We encountered 2 main problems when tried deploy temporal-operator in our k8s clusters.
1. In our clusters we have adminission controler that checks resource limits on every pod in the cluster. If you don't pass resource limits for pod you will not able to deploy it.
2. We work with s3 compatible storage provider that supports only path styled url's.
To resolve it I did:
1. Added ability to pass resources for init jobs from CRD.
2. Added ability to pass s3PathStyle from CRD.
=> Set resources for jobs and s3ForcePathStyle for archiver

internal/resource/persistence/template.go, internal/resource/persistence/template_test.go
Persistence scripts such as create database did not include the command to shut down the underlying proxies. This MR should fix that.
=> Fix persistence scripts that are missing shutdown

internal/resource/prometheus/scrape_annotations.go
This MR is to fix the Prometheus scraping port. The pointer address of `instance.Spec.Metrics.Prometheus.ListenPort` was used instead of the pointed value, which in turn caused pod crashing loop
=> Fix Prometheus scraping port

examples/cluster-mtls/02-temporal-cluster.yaml, internal/resource/admintools/deployment_builder.go, internal/resource/mtls/certmanager/env.go
=> fix(admintools): add mtls environment variables for temporal cli >= 0.9.0

internal/resource/config/configmap_builder.go, pkg/version/version.go
=> fix(config): only set frontend HTTP port if not nil

api/v1beta1/temporalcluster_defaults.go, internal/resource/base/headless_service_builder.go
- fix `refreshInterval` default when using istio mTLS (not cert-manager)
- fix istio mTLS for Uber Ringpop: those two ports need to be explicitly listed in headless services otherwise Ringpop p2p cannot communicate with each other and result in bootstrap failure and container restarts
=> Fix istio mTLS

api/v1beta1/temporalcluster_types.go, config/crd/bases/temporal.io_temporalclusters.yaml, internal/resource/config/configmap_builder.go, webhooks/temporalcluster_webhook.go
Close: #565 
Add support for Metrics PerUnitHistogramBoundaries config. Locally tested successful with the config below.
```
metrics:
enabled: true
perUnitHistogramBoundaries:
dimensionless:
- "51200"  
- "100000"
milliseconds:
- "500000"
- "1000000"
bytes:
- "2097152"
- "4194304"
=> feat(config): add support for Metrics PerUnitHistogramBoundaries config

README.md
In order to use github pages for helm releases, I moved the documentation site to cloudflare pages.
=> Update README.md with new documentation site

api/v1beta1/temporalcluster_types.go, config/crd/bases/temporal.io_temporalclusters.yaml, docs/api/v1beta1.md, webhooks/temporalcluster_webhook.go
=> feat(webhook): Only allow Elasticsearch datastore type for advancedVisibility on clusters => 1.21

api/v1beta1/temporalcluster_types.go, internal/resource/persistence/utils_test.go
=> fix(persistence): ensure unique mount paths for datastore tls ca, cert, and key

examples/cluster-cassandra/02-temporal-cluster.yaml
=> fix(example): remove disableInitialHostLookup config key in cassandra example

.github/workflows/e2e.yaml, tests/e2e/kind_provider_test.go, tests/e2e/main_test.go
=> test: fix e2e test kind setup

charts/temporal-operator/templates/manager-rbac.yaml
This PR fixes missing permissions for the helm chart (recent addition of [schedules support](https://github.com/alexandrevilain/temporal-operator/pull/736) and [configmap deletion](https://github.com/alexandrevilain/temporal-operator/pull/739)).
=> fix(rbac): add missing permissions to helm clusterrole

controllers/temporalschedule_controller.go
This fixes an incorrectly indexed field in the `TemporalSchedule` controller that is used for watching `TemporalNamespace` for changes
=> fix(controller): Fixed TemporalSchedule namespace watcher

docs/contributing/local-development.md
Changes:
- add missing dependencies
- add directions for local temporal setup
- add information on available test commands
=> docs: enhance details & directions

docs/api/v1beta1.md
Not sure if this is a recent change, but current links (using `/operator/` path segment) result in 404; just subbing it for `/api-reference/` does the trick.
=> Updating links to Prometheus Operator docs in PrometheusScrapeConfigServiceMonitor

Makefile, charts/temporal-operator/Chart.yaml, charts/temporal-operator/README.md, charts/temporal-operator/crds/temporal-operator.crds.yaml, config/crd/bases/temporal.io_temporalclusters.yaml
This bumps the app version to v0.20.0 and updates the `prepare-release` task in the `Makefile` to update the `appVersion` in the Helm chart.
=> Helm chart: bump app version to v0.20.0

Makefile
sed behaves different on MacOS vs Ubuntu on Github Action (BSD vs GNU).
Chart release [seems to have failed](https://github.com/alexandrevilain/temporal-operator/actions/runs/12081336220/job/33690239625) because of this.
This makes it safe to run it on both platforms.
=> fix(build): Adapt GNU/BSD sed in Makefile

.github/workflows/release-chart.yaml
To force manual chart release after fix in 6eef5d06823ed7a6f69685ed2cd02c7c6aea2183:
This should make it possible to manually trigger the chart release workflow.
=> fix: Add manual workflow trigger

docs/features/admin-tools.md, pkg/version/admintools.go, pkg/version/admintools_test.go
1.23.1 tag does not exist for admintools so the pod gets stuck in ImagePullBackOff error state: https://hub.docker.com/r/temporalio/admin-tools/tags?name=1.23
=> fix(admintools): add defaults for v1.23.x

api/v1beta1/temporalcluster_types.go
Implements [957](https://github.com/alexandrevilain/temporal-operator/issues/957)
- The GetPublicClientAddress method was always returning the frontend service address regardless of whether internal frontend was enabled.
- This caused authentication issues for internal operations like creating the default namespace when auth was configured on the public frontend.
```
2025-09-01T06:55:20Z	INFO	Starting reconciliation	{"controller": "temporalnamespace", "controllerGroup": "temporal.io", "controllerKind": "TemporalNamespace", "TemporalNamespace": {"name":"default","namespace":"temporal"}, "namespace": "temporal", "name": "default", "reconcileID": "38d32796-6ead-41a1-adb0-e60f629eb8dd"}
2025-09-01T06:55:20Z	DEBUG	Connecting to temporal cluster	{"controller": "temporalnamespace", …
```
=> fix: use internal frontend in GetPublicClientAddress when enabled
