config/rbac/role.yaml
controllers/temporalcluster_controller.go
pkg/cluster/cluster.go
pkg/resource/builder.go
pkg/resource/ui_ingress_builder.go

feat: prune resources when they are disabled

---

api/v1alpha1/temporalcluster_types.go
config/crd/bases/apps.alexandrevilain.dev_temporalclusters.yaml
controllers/reconcile_defaults.go
controllers/temporalcluster_controller.go
controllers/temporalclusterclient_controller.go
docs/api/v1alpha1.md
examples/cluster-mtls-linkerd/00-namespace.yaml
examples/cluster-mtls-linkerd/01-postgresql.yaml
examples/cluster-mtls-linkerd/02-temporal-cluster.yaml
pkg/cluster/cluster.go
pkg/resource/admintools_deployment_builder.go
pkg/resource/configmap_builder.go
pkg/resource/deployment_builder.go
pkg/resource/linkerd/inject.go
pkg/resource/ui_deployment_builder.go

Add support for linkerd as mTLS provider

---

bundle/manifests/temporal-operator.clusterserviceversion.yaml

Signed-off-by: ktenzer <keith.tenzer@gmail.com>

#146 updated clusterserviceversion to 0.7.0

---

bundle/manifests/temporal-operator.clusterserviceversion.yaml
config/manifests/bases/temporal-operator.clusterserviceversion.yaml

Signed-off-by: ktenzer <keith.tenzer@gmail.com>

Updated ClusterServiceVersion for Operatorhub release v0.9.1

---

bundle/manifests/temporal-operator.clusterserviceversion.yaml
config/manifests/bases/temporal-operator.clusterserviceversion.yaml

Signed-off-by: ktenzer <keith.tenzer@gmail.com>

updated containerImage and replaces field in CSV for 0.10.0

---

api/v1beta1/temporalnamespace_types.go
config/crd/bases/temporal.io_temporalnamespaces.yaml
controllers/temporalnamespace_controller.go
docs/api/v1beta1.md
examples/cluster-postgres/03-temporal-namespace.yaml
pkg/temporal/namespace.go
tests/e2e/main_test.go
tests/e2e/namespace_test.go

Add support for namespace deletion

---

pkg/kubernetes/secret_test.go

Add unit tests for SecretCopier

---

README.md
api/v1beta1/temporalcluster_types.go
bundle/manifests/temporal-operator.clusterserviceversion.yaml
config/crd/bases/temporal.io_temporalclusters.yaml
config/manifests/bases/temporal-operator.clusterserviceversion.yaml
config/samples/temporal.io_v1beta1_temporalcluster.yaml
docs/dynamic_config.md
docs/monitoring.md
examples/cluster-cassandra/02-temporal-cluster.yaml
examples/cluster-mtls-linkerd/02-temporal-cluster.yaml
examples/cluster-postgres-es/03-temporal-cluster.yaml
examples/cluster-postgres/01-postgresql.yaml
examples/cluster-postgres/02-temporal-cluster.yaml
pkg/resource/configmap_builder.go
pkg/resource/persistence/schema_scripts_configmap_builder.go
tests/e2e/persistence_test.go
tests/e2e/testdata/postgres/deployment.yaml
webhooks/temporalcluster_webhook.go

Add support for new sql plugins: mysql8 and postgres12

---

docs/features/admin-tools.md
docs/features/mtls/linkerd.md
docs/features/overrides.md
docs/features/temporal-ui.md
docs/wip.md
examples/cluster-postgres/02-temporal-cluster.yaml
mkdocs.yml
pkg/resource/overrides.go
pkg/resource/overrides_test.go

Document how we can add sidecar and init container using overrides

---

.github/workflows/e2e.yaml
Makefile
config/samples/temporal.io_v1beta1_temporalworkerprocess.yaml
examples/worker-process/helloworld/Dockerfile
tests/e2e/main_test.go
tests/e2e/workerprocess_test.go

Use local example-worker-process in e2e

---

.github/workflows/e2e.yaml
Makefile
api/v1beta1/temporalcluster_defaults.go
api/v1beta1/temporalcluster_types.go
config/crd/bases/temporal.io_temporalclusters.yaml
examples/cluster-postgres-es/03-temporal-cluster.yaml
go.mod
internal/resource/persistence/schema_scripts_configmap_builder.go
internal/resource/persistence/template.go
tests/e2e/main_test.go
tests/e2e/persistence_test.go
tests/e2e/testdata/elasticsearch/elasticsearch.yaml
tests/e2e/utils_test.go

Add support for Elasticsearch v8 (with e2e tests)

---

api/v1beta1/temporalcluster_types.go
api/v1beta1/temporalnamespace_types.go
controllers/temporalclusterclient_controller.go
controllers/temporalnamespace_controller.go
controllers/temporalworkerprocess_controller.go
tests/e2e/assert_test.go
tests/e2e/namespace_test.go
tests/e2e/utils_test.go

fix: wait for TemporalCluster ready for reconciliation using cluster reference

---

bundle/manifests/temporal-operator.clusterserviceversion.yaml

change default resources.limits/requests for temporal-operator at issue #413
Closes #413

Increase default resources limits & requests for controller

---

api/v1beta1/temporalcluster_types.go
config/crd/bases/temporal.io_temporalclusters.yaml
docs/api/v1beta1.md
internal/resource/persistence/schema_scripts_configmap_builder.go
internal/resource/persistence/template.go

Add option to skip create database or keyspace

---

api/v1beta1/temporalcluster_defaults.go
api/v1beta1/temporalcluster_types.go
config/crd/bases/temporal.io_temporalclusters.yaml
controllers/reconcile_persistence.go
internal/resource/base/configmap_builder.go
internal/resource/persistence/schema_scripts_configmap_builder.go
internal/resource/persistence/template.go
pkg/version/version.go
tests/e2e/persistence_test.go
webhooks/temporalcluster_webhook.go
webhooks/temporalcluster_webhook_test.go

Add support for temporal v1.21.x and  support for Advanced visibility on SQL DBs

---

examples/cluster-postgres/01-postgresql.yaml
examples/cluster-postgres/02-temporal-cluster.yaml
internal/resource/persistence/schema_scripts_configmap_builder.go

fix: support database users with dashes

---

.github/workflows/release.yaml
Dockerfile

feat: publish arm64 docker images

---

internal/resource/admintools/deployment_builder.go

Export `TEMPORAL_ADDRESS ` in admintools for `temporal` CLI

---

docs/features/archival.md

* principals are not mandatory for role policy
* typo of enableRead
* clarify the service account to trust

Amend documents for archival

---

controllers/temporalnamespace_controller.go

Tolerate namespace not found error when deleting

---

controllers/temporalnamespace_controller.go
pkg/temporal/namespace.go

Support namespace update

---

controllers/reconcile_persistence.go

fix(persistence): fix secondary visibility store status reporting

---

controllers/temporalnamespace_controller.go

fix(TemporalNamespace): enqueue namespace reconcile when referenced TemporalCluster is updated

---

api/v1beta1/temporalcluster_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/temporal.io_temporalclusters.yaml
controllers/reconcile_persistence.go
docs/api/v1beta1.md
examples/cluster-postgres/02-temporal-cluster.yaml
go.mod

fix(persistence): support SQL plugin upgrade

---

controllers/reconcile_persistence.go

fix(persistence): reduce persistence job name length

---

docs/features/overrides.md
docs/features/temporal-ui.md

Add docs about overriding UI deployment

---

Makefile
bundle/manifests/temporal-operator.clusterserviceversion.yaml
config/manifests/bases/temporal-operator.clusterserviceversion.yaml
hack/operatorhub.sh

chore(tooling): Add script to publish release to OperatorHub

---

pkg/kubernetes/secret.go
pkg/kubernetes/secret_test.go

fix(SecretCopier): update secret when orginal secret is updated

---

README.md
api/v1beta1/temporalcluster_types.go
config/crd/bases/temporal.io_temporalclusters.yaml
docs/api/v1beta1.md
internal/resource/persistence/schema_scripts_configmap_builder.go

As suggested in #553.
works with my cluster.
Thank you for hand holding @alexandrevilain

fix(): making datacenter property optional for cassandra, temporary fix for #553

---

docs/features/temporal-ui.md

Add ui docs description

---

controllers/temporalclusterclient_controller.go

fix(TemporalClusterClient): requeue reconcile when certificate is updated

---

api/v1beta1/temporalworkerprocess_types.go
config/crd/bases/temporal.io_temporalclusters.yaml
config/crd/bases/temporal.io_temporalworkerprocesses.yaml

feat(api): Deprecate TemporalWorkerProcess API

---

charts/temporal-operator/Chart.yaml
charts/temporal-operator/templates/deployment.yaml
charts/temporal-operator/values.yaml

- Adding support for tolerations and nodeSelector, to scratch my own itch.
- Bump version of the Chart
- Bump appVersion to latest version

Support for tolerations and nodeSelector in Helm Chart

---

controllers/temporalnamespace_controller.go
tests/e2e/namespace_test.go

Allow deleting TemporalNamespace when referenced TemporalCluster does not exist. Currently, it just gets stuck waiting for the TemporalCluster.
Related to: #552 #665

fix: TemporalNamespace resource deletion

---

internal/resource/persistence/utils.go
internal/resource/persistence/utils_test.go

fix(persistence): duplicated volume mount path for key file

---

internal/resource/base/deployment_builder.go
internal/resource/base/frontend_service_builder.go

fix(frontend): expose http port on frontend service

---

Makefile
api/v1beta1/temporalcluster_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/temporal.io_temporalclusters.yaml
docs/api/v1beta1.md
docs/features/overrides.md
pkg/kubernetes/overrides.go
pkg/kubernetes/overrides_test.go

feat: support strategic merge patch in overrides

---

internal/resource/admintools/deployment_builder.go
internal/resource/base/deployment_builder.go
internal/resource/persistence/schema_setup_job_builder.go
internal/resource/ui/deployment_builder.go

Closes #731 
Simple change to pull policy

feat(config): change in image pull policy to pull if not present

---

internal/resource/ui/deployment_builder.go

Fixes issue #730 
Added extra params to SecurityContext.

feat(config): run temporal ui as non-root temporal user

---

config/rbac/role.yaml
controllers/temporalcluster_controller.go

fix(rbac): allow controller to delete dynamic config configmap
